feat: Healthcare Package
earthians/marley pull request #526
Opened 2024-12-01 07:40 UTC by Sajinsr

### Healthcare Package
`Healthcare > Healthcare Package`

- Introduced to allow healthcare providers to offer a set of services in a single, organized manner
- Reduces the administrative overhead of billing for multiple standalone services
- Provision create Healthcare Package with selected services and it will fetch all item details
- Provision apply discount for the package item, also can apply discount on item level
- Option to enable `Item wise Invoicing` in billing section. If checked, billing will happen against each package items

`Healthcare > Package Subscription`
- Introduced to assign the Healthcare Package to a patient with a validity
- Provision collect advance payment from here itself
- Sales invoice will fetch package items to bill

![healthcare-package](https://github.com/user-attachments/assets/3fc34996-7d53-447b-ad80-3bd9e285129f)

2024-12-03 11:40 UTC, akurungadam requested changes

2024-12-03 11:40 UTC, akurungadam commented on healthcare/healthcare/doctype/package_subscription/test_package_subscription.py
> +	pass
add tests?

2024-12-03 11:40 UTC, akurungadam commented on healthcare/healthcare/doctype/package_subscription/package_subscription.py
> +		if self.total_package_amount:
let's not allow payment unless the subscription is submitted?

2024-12-03 11:40 UTC, akurungadam commented on healthcare/healthcare/doctype/healthcare_package/healthcare_package.js
> +let package_docs_filter = ["Item","Clinical Procedure Template", "Observation Template", "Therapy Type"]
can't we make this user configurable?

2024-12-03 11:40 UTC, akurungadam commented on healthcare/healthcare/doctype/healthcare_package/healthcare_package.js
> +			frm.doc.discount_amount = 0;
`frm.set_value("discount_amount", 0)`

2024-12-03 11:40 UTC, akurungadam commented on healthcare/healthcare/doctype/healthcare_package/healthcare_package.js
> +			frm.doc.additional_discount_percentage = 0;
`frm.set_value("additional_discount_percentage", 0)`

2024-12-05 10:19 UTC, Sajinsr commented on healthcare/healthcare/doctype/package_subscription/test_package_subscription.py
> +	pass
Test cases added for subscriptions

2024-12-06 03:00 UTC, Sajinsr commented on healthcare/healthcare/doctype/healthcare_package/healthcare_package.js
> +let package_docs_filter = ["Item","Clinical Procedure Template", "Observation Template", "Therapy Type"]
At this stage, making this as pre-defined, will take this into consideration for future updates

2024-12-23 09:24 UTC, akurungadam approved these changes

2025-04-25 15:22 UTC, 3likayed commented
any good news ?

2025-08-07 18:27 UTC, johnwslongland commented
This sounds like a good idea.

2026-07-04 05:00 UTC, closed without merging